services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=my-elastic-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ES_USER}
      - ELASTIC_PASSWORD=${ES_PASS}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es01/es01.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
      - xpack.security.http.ssl.enabled=true
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elastic/certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=my-elastic-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ES_USER}
      - ELASTIC_PASSWORD=${ES_PASS}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es02/es02.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es02/es02.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es02/es02.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es02/es02.crt
      - xpack.security.http.ssl.certificate_authorities=["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
      - xpack.security.http.ssl.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - '9201:9200'
      - '9301:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elastic/certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=my-elastic-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ES_USER}
      - ELASTIC_PASSWORD=${ES_PASS}
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/es03/es03.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/es03/es03.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/es03/es03.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/es03/es03.crt
      - xpack.security.http.ssl.certificate_authorities=["/usr/share/elasticsearch/config/certs/ca/ca.crt"]
      - xpack.security.http.ssl.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - '9202:9200'
      - '9302:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
      - ./elastic/certs:/usr/share/elasticsearch/config/certs
    networks:
      - elastic

volumes:
  esdata1:
  esdata2:
  esdata3:

networks:
  elastic:
    driver: bridge
